DATATROVE_COLORIZE_LOGS=0
DATATROVE_COLORIZE_LOG_FILES=0

ROOT_DIR=/home/biar/Desktop/PIPELINE/ita-llm-pipeline
DATA_DIR=/home/biar/Desktop/PIPELINE/ita-llm-pipeline/data
OUTPUT_DIR=/home/biar/Desktop/output_data
REJECTED_DIR=/home/biar/Desktop/output_data/rejected
